### PR TITLE
Serialize ids as strings

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
Looking at the `IntegerField` implementation, I'm wondering if we should inherit from that instead: https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/fields.py#L818 , and just replace its `to_representation` command with the one above, since it does some other useful checks (like guarding against malicious strings, and descriptive error messages).

At the moment we won't use any of these, since it's a read only field, I just think it would be nice to guard against it if in the future we use the field in a non read-only matter.

**Comment by rudigiesler** [comment]
Also, I think maybe the docs need to be updated? Other than that, looks good to me :)

**Comment by justinvdm** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
