### PR TITLE
Support pagination with next and prev in link header

### PR DESCRIPTION
**Pull request by justinvdm**

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler ready for review

**Comment by rudigiesler** [comment]
I think we might need to change `.travis.yml` in order for these tests to actually be run. Probably something like `--ignore=authapi/migrations authapi`, and moving the existing tests into the `tests` folder and renaming it `test_api.py` or something like that.

This PR looks good to me otherwise.

**Comment by justinvdm** [comment]
Ready for re-review.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
