### PR TITLE
Return organization summary when getting a team

### PR DESCRIPTION
**Pull request by rudigiesler**
At the moment we return an organization id, but it would be useful to return a summary of the organization.

### CODE REVIEW

**Comment by rudigiesler** [comment]
@justinvdm Ready for review.

**Comment by rudigiesler** [comment]
With https://github.com/praekelt/seed-auth-api/pull/16 , this PR will have to change (will probably simplify).

**Comment by rudigiesler** [comment]
With https://github.com/praekelt/seed-auth-api/pull/16, this PR will likely have to change, since we no longer wish to be able to set/change the organization of a team, it should only be set during creation.

**Comment by rudigiesler** [comment]
Actually, now that I think of it, I don't think that we need to change anything here. @justinvdm Ready for review.

**Comment by justinvdm** [comment]
I think `organization` should change to a read only field. So we don't allow changing the organization via `PUT`s, and we can read the organization summary by viewing `organization` on `GET`s.

**Comment by rudigiesler** [comment]
@justinvdm Changed `organization` to be a create-only field. Ready for another review.

**Comment by justinvdm** [comment]
@rudigiesler if I'm looking correctly, I think there are stray `int organization`s for `POST /organizations/<id>/teams/` and `PUT /teams/<id>`.

**Comment by rudigiesler** [comment]
@justinvdm Yes you're correct. I've updated the docs. Ready for review again.

**Comment by justinvdm** [comment]
:+1:

**Comment by rudigiesler** [comment]
@justinvdm Sorry, saw that I didn't add a test for blocking updating of the team's organization. Can you check the last commit?

**Comment by justinvdm** [comment]
:+1:

**Pull request merged**
