### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@smn @rudigiesler @justinvdm ready for review. If this could be published to the internal docker registry on landing that would be A+++

**Comment by imsickofmaps** [comment]
resolves #41

**Comment by rudigiesler** [comment]
No idea why the tests are failing, but :+1: from me. (I don't know how to publish this to the internal docker registry)

**Comment by imsickofmaps** [comment]
@rudigiesler would you mind landing it? I can't 😢

**Pull request merged**
