### PR TITLE
Add introduction to docs

### PR DESCRIPTION
**Pull request by justinvdm**
We need to add info to the docs about what problem seed-auth-api is solving, how it solves it, and how one could use it for their service.

### CODE REVIEW

**Comment by justinvdm** [comment]
@rudigiesler ready for review

Struggled a bit to summarise how the api is used, I think the only way to make that clearer would be to add a tutorial or getting started section of some sort, but that is more than we have time for at the moment.

**Comment by rudigiesler** [comment]
I'm wondering if we should maybe put this on the index page? Since the index page just contains the contents of the http api page, it might be nice to have it there?

Other thank that, content looks good 😄

**Comment by justinvdm** [comment]
Ready for re-review.

**Comment by rudigiesler** [comment]
:+1:

**Pull request merged**
